name: tomat_os
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  battery_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts: 
        - asset: assets/fonts/Inter-Variable.ttf
        - asset: assets/fonts/Inter-Italic.ttf
          style: italic
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Variable.ttf
        - asset: assets/fonts/JetBrainsMono-Italic.ttf
          style: italic